# Generated by Django 5.0.7 on 2024-07-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.ManyToManyField(to='my_app.link'),
        ),
    ]
