# Generated by Django 5.0.7 on 2024-07-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_menu_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
