# Generated by Django 5.0.7 on 2024-07-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_link_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='priority',
            new_name='position',
        ),
    ]
