# Generated by Django 5.0.7 on 2024-07-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_priority_link_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='position',
        ),
    ]
